spring:
  application:
    name: greeting-service

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - refresh

greeting-service:
  greeting: "Hello"
  default-value: "World"

