spring:
  application:
    name: greeting-service

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - refresh

greeting-service:
  greeting: "Ciao"
  default-value: "Mondo"

